api:
  address: 0.0.0.0:8080
  allow_origins:
    - '*'
  member_file: data/data/members.yaml
  jwt_expire_day: 7
cache:
  root: ./data/api/cache
  uuid_file: uuid.json
log:
  root: DEBUG
  with_color: true
